general {
    lock_cmd = $HOME/.config/hypr/lock
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = hyprctl dispatch 'hl.dsp.dpms("on")'
}

listener {
    timeout = 600
    on-timeout = loginctl lock-session
}

listener {
    timeout = 900
    on-timeout = hyprctl dispatch 'hl.dsp.dpms("off")'
    on-resume = hyprctl dispatch 'hl.dsp.dpms("on")'
}
